apiVersion: events.kabanero.io/v1alpha1
kind: EventMediations
metadata:
  name: webhook-switchboard
spec:
  mediations:
    - mediation:
        name: webhook-switchboard
        input: message
        sendTo: [ "githubDest" , "dockerDest", "defaultDest" ]
        body:
          - switch:
              - if: 'has(message.header["X-Github-Event"])'
                = : 'sendEvent(githubDest, message.body, filterGithubHeader(message.header))'
              - if : 'has(message.callback_url) && message.callback_url.matches("*docker*") '
                = : 'sendEvent(dockerDest, message.body, message.header)'
              - default:
                = : 'sendEvent(defaultDest, message.body, message.header)'
