apiVersion: events.kabanero.io/v1alpha1
kind: EventMediator
metadata:
  name: https-listener
spec:
  listeners:
    - httpsPort: 9443
      createService: true
      createRoute: true
  mediations:
    - mediation:
        name: listener1
        sendTo: [ "dest" ]
        body:
          = : 'sendEvent(dest, message.body, message.header)'
