apiVersion: events.kabanero.io/v1alpha1
kind: EventMediations
metadata:
  name: library1
spec:
  mediations:
    - mediation:
        name: github-event-switchboard
        sendTo: [ "githubDest" , "otherDest" ]
        body:
          - switch:
              - if: 'has(message.header["X-Github-Event"])'
                = : 'sendEvent(githubDest, message.body, filterGithubHeader(message.header))'
              - default:
                = : 'sendEvent(otherDest, message.body, message.header)'
    - function:
        name: filterGithubHeader
        input: inputHeader
        output: outputHeader
        body:
          = : 'outputHeader = filter(inputHeader, ""key.startsWith(\"X-Github\") || key == \"X-Hub-Signature\" " )'
