apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventmediators.events.kabanero.io
spec:
  group: events.kabanero.io
  names:
    kind: EventMediator
    listKind: EventMediatorList
    plural: eventmediators
    singular: eventmediator
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EventMediator is the Schema for the eventmediators API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EventMediatorSpec defines the desired state of EventMediator
          properties:
            code:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  function:
                    properties:
                      body:
                        items:
                          description: ' Valid combinations are:   1) assignment   2)
                            if and assignment   3) if and body   4) switch   5) if
                            and switch   TBD: switch and default'
                          properties:
                            =:
                              type: string
                            '?':
                              type: string
                            body:
                              items: {}
                              type: array
                            switch:
                              items: {}
                              type: array
                          required:
                          - =
                          - '?'
                          - body
                          - switch
                          type: object
                        type: array
                      input:
                        type: string
                      name:
                        type: string
                      output:
                        type: string
                    required:
                    - body
                    - input
                    - name
                    - output
                    type: object
                  mediation:
                    properties:
                      body:
                        items:
                          description: ' Valid combinations are:   1) assignment   2)
                            if and assignment   3) if and body   4) switch   5) if
                            and switch   TBD: switch and default'
                          properties:
                            =:
                              type: string
                            '?':
                              type: string
                            body:
                              items: {}
                              type: array
                            switch:
                              items: {}
                              type: array
                          required:
                          - =
                          - '?'
                          - body
                          - switch
                          type: object
                        type: array
                      name:
                        type: string
                      sendTo:
                        items:
                          type: string
                        type: array
                      subscribeFrom:
                        items:
                          type: string
                        type: array
                    required:
                    - body
                    - name
                    - sendTo
                    - subscribeFrom
                    type: object
                required:
                - function
                - mediation
                type: object
              type: array
          required:
          - code
          type: object
        status:
          description: EventMediatorStatus defines the observed state of EventMediator
          properties:
            message:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - message
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
