apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-operator
  namespace: kabanero
subjects:
- kind: ServiceAccount
  name: events-operator
  namespace: kabanero
roleRef:
  kind: Role
  name: events-operator
  apiGroup: rbac.authorization.k8s.io
