apiVersion: events.kabanero.io/v1alpha1
kind: EventConnections
metadata:
  name: example1
spec:
  connections:
    - from:
        group: events.kabanero.io
        kind: EventMediator
        name: webhook
        id: webhook 
      to:
        - https:
            - url: https://mediator1/mediation1
              insecure: true
