apiVersion: events.kabanero.io/v1alpha1
kind: EventMediator
metadata:
  name: mediator1
spec:
  createListener: true
  mediations:
    - mediation:
        name:  mediation1
        sendTo: [ "dest"  ]
        body:
          - = : 'sendEvent(dest, body, header)'
