apiVersion: events.kabanero.io/v1alpha1
kind: EventMediator
metadata:
  name: webhook
spec:
  createListener: true
  createRoute: true
  mediations:
    - name: webhook
      variables:
        - name: "body.variable1"
          valueExpression: 'hasAttribute("header.Git-Enterprise") ? "ghe" : "github"'
        - name: "body.variable2"
          valueExpression: 'hasAttribute("header.git1-ent") ? "ghe" : "github"'
      sendTo: [ "dest"  ]
      body:
        - = : 'sendEvent(dest, body, header)'
