apiVersion: events.kabanero.io/v1alpha1
kind: EventMediator
metadata:
  name: webhook
spec:
  createListener: true
  createRoute: true
  mediations:
    - mediation:
        name: webhook
        input: message
        sendTo: [ "dest"  ]
        body:
          - = : 'sendEvent(dest, message.body, message.header)'
