apiVersion: events.kabanero.io/v1alpha1
kind: EventMediator
metadata:
  name: webhook
spec:
  createListener: true
  createRoute: true
  mediations:
    - name: webhook
      sendTo: [ "dest"  ]
      body:
        - = : 'sendEvent(dest, body, header)'
