apiVersion: events.kabanero.io/v1alpha1
kind: EventConnections
metadata:
  name: connections2
spec:
  connections:
    - from: 
        mediator:
            name: webhook2
            mediation: webhook
            destination: dest
      to:
        - https:
            - url: https://mediator2-1/mediation1
              insecure: true
            - urlExpression:  body["webhooks-kabanero-tekton-listener"]
              insecure: true
    - from: 
        mediator:
            name: webhook2
            mediation: gitops
            destination: dest
      to:
        - https:
            - url: https://mediator2-1/mediation1
              insecure: true
            - urlExpression:  eventListenerURL("deploy-kustomize-listener")
              insecure: true
