apiVersion: v1
kind: Secret
metadata:
  name: ghe-https-secret
  annotations:
    tekton.dev/git-0: https://github.ibm.com
type: kubernetes.io/basic-auth
stringData:
  username: mcheng.us.ibm.com
  password:  fa9737e13f9c7688381bae20430d2148ed5b171f
