apiVersion: events.kabanero.io/v1alpha1
kind: EventMediator
metadata:
  name: mediator2-1
spec:
  createListener: true
  mediations:
    - name:  mediation1
      sendTo: [ "dest"  ]
      body:
        - = : 'sendEvent(dest, body, header)'
